const projectERecipeIdsToRemove = [
	'projecte:transmutation_table',
	'projecte:transmutation_tablet',
	'projecte:divining_rod_1',
	'projecte:divining_rod_2',
	'projecte:divining_rod_3',
	'projecte:dm_pick',
	'projecte:dm_axe',
	'projecte:dm_shovel',
	'projecte:dm_hoe',
	'projecte:dm_shears',
	'projecte:dm_hammer',
	'projecte:rm_pick',
	'projecte:rm_axe',
	'projecte:rm_shovel',
	'projecte:rm_hoe',
	'projecte:rm_shears',
	'projecte:rm_hammer',
	'projecte:dm_sword',
	'projecte:rm_sword',
	'projecte:rm_katar',
	'projecte:rm_morning_star',
	'projectextended:dark_matter_trident',
	'projectextended:red_matter_trident',
	'projectextended:dark_matter_shield',
	'projectextended:red_matter_shield',
	'projecte:gem_helmet',
	'projecte:gem_chestplate',
	'projecte:gem_leggings',
	'projecte:gem_boots',
	'projecte:dm_helmet',
	'projecte:dm_chestplate',
	'projecte:dm_leggings',
	'projecte:dm_boots',
	'projecte:rm_helmet',
	'projecte:rm_chestplate',
	'projecte:rm_leggings',
	'projecte:rm_boots',
	'projecte:watch_of_flowing_time',
	'projecte:evertide_amulet',
	'projecte:volcanite_amulet',
	'projecte:void_ring',
	'projecte:arcana_ring',
	'projecte:gem_of_eternal_density',
	'projecte:destruction_catalyst',
	'projecte:mercurial_eye',
	'projecte:archangel_smite',
];

ServerEvents.recipes(event => {
    projectERecipeIdsToRemove.forEach ( recipeId => {
        event.remove({id: recipeId})
    });
});